### ISSUE TITLE
Instruction access fault on illegal PCs not being thrown

### ISSUE THREAD

**Issue by jerryz123** [SpinalHDL/VexiiRiscv#28]
The rv64mi-p-breakpoint test flips the high-bit of a valid PC addres in RV64, creating an illegal address, then executes a `jalr` to that address. This should result in an instruction access fault, but VexiiRiscv seems to discard the high bit instead.

The first test case here fails: https://github.com/riscv-software-src/riscv-tests/blob/master/isa/rv64mi/access.S

**Comment by Dolu1990** [comment]
Hi, 

I pushed a few changes. This should now be good.
Let's me know if you encounter any issues, as i didn't had access to the same regressions tests (mostly i do not run the proxy kernel)
